# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

BOARD_TAG    = mega
BOARD_SUB    = atmega2560
MONITOR_PORT = /dev/tty.usbmodem14331
ARDUINO_DIR  = /Applications/Arduino.app/Contents/Java
include /usr/local/Cellar/arduino-mk/1.5.2/Arduino.mk