# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

BOARD_TAG    = mega
BOARD_SUB    = atmega2560
MONITOR_PORT = /dev/cu.usbmodemFA131
# MONITOR_PORT = /dev/tty.usbmodemFD121
ARDUINO_DIR  = /Applications/Arduino.app/Contents/Java
include /usr/local/arduino/Arduino-Makefile/Arduino.mk
